<?php // CONFIG AUTOGENERATED BY THE INSTALLER

dbData::$host = 'localhost';
dbData::$user = 'root';
dbData::$pass = '';
dbData::$db = 'linkeros';
/*
dbData::$host = 'localhost';
dbData::$user = 'linkeros';
dbData::$pass = 'BAVSBFmj8C4X9Uv2';
dbData::$db = 'linkeros';


dbData::$host = 'localhost';
dbData::$user = 'linkeros_main';
dbData::$pass = '=tqbt!vC76tt';
dbData::$db = 'linkeros_main';*/

_::$globals['WEB_LINK'] = 'http://localhost';
_::$globals['WEB_SITE'] = 'Linkeros!';
_::$globals['WEB_LEMA'] = 'Todas tus descargas';
_::$globals['descripcion'] = 'Web de descargas, links, mega';
_::$globals['autor'] = '';

//$_SESSION['themeSelected'] = 'v9';
// Theme default:

if(!isset($_SESSION['themeSelected']) || $_SESSION['themeSelected'] == 'v9')
{
    coreData::$v = 'themes/default/';
    _::$globals['theme_location'] = _::$globals['WEB_LINK'].'/themes/default/';
} else {
    // si es la v4
    if($_SESSION['themeSelected'] == 'v4'){
        coreData::$v = 'themes/v4/';
        _::$globals['theme_location'] = _::$globals['WEB_LINK'].'/themes/v4/';
        tplData::$cacheDir = DIR54.'/cache_v4/';
    }
}
/*
if(!isset($_SESSION['themeSelected'])  || $_SESSION['themeSelected'] == 'v4')
{
    coreData::$v = 'themes/v4/';
    _::$globals['theme_location'] = _::$globals['WEB_LINK'].'/themes/v4/';
    tplData::$cacheDir = DIR54.'/cache_v4/';
    
} else {
    // si es la v4
    if($_SESSION['themeSelected'] == 'v9'){
        coreData::$v = 'themes/default/';
        _::$globals['theme_location'] = _::$globals['WEB_LINK'].'/themes/default/';
    }
}*/