<?php
// instalador anulado
die('NULL');

_::define_controller('install', function(){
	// welcome
	_::$view->assign('script', 'Linkeros');
	_::$view->show('install/index');
});

_::define_controller('install_ajax', function(){
	
	if(isset(_::$post['file']) && (string)_::$post['file'] == 'true')
	{
		// make settings.php
		$dbhost = (string)_::$post['db_host'];
		$dbuser = (string)_::$post['db_user'];
		$dbpass = (string)_::$post['db_pass'];
		$dbname = (string)_::$post['db_name'];
		
		$link = (string)_::$post['link'];
		$title = (string)_::$post['title'];
		
		$config = '<?php // CONFIG AUTOGENERATED BY THE INSTALLER'.PHP_EOL;
		$config .= PHP_EOL;
		$config .= "dbData::\$host = '$dbhost';".PHP_EOL;
		$config .= "dbData::\$user = '$dbuser';".PHP_EOL;
		$config .= "dbData::\$pass = '$dbpass';".PHP_EOL;
		$config .= "dbData::\$db = '$dbname';".PHP_EOL;
		$config .= PHP_EOL;
		$config .= '// Theme default:'.PHP_EOL;
		$config .= 'coreData::$v = \'themes/default/\';'.PHP_EOL;
		$config .= PHP_EOL;
		$config .= "_::\$globals['WEB_LINK'] = '$link';".PHP_EOL;
		$config .= "_::\$globals['WEB_SITE'] = '$title';".PHP_EOL;
		$config .= "_::\$globals['WEB_LEMA'] = 'Inteligencia colectiva';".PHP_EOL;
		$config .= "_::\$globals['theme_location'] = _::\$globals['WEB_LINK'].'/themes/default/';".PHP_EOL;
		$config .= "_::\$globals['descripcion'] = '';".PHP_EOL;
		$config .= "_::\$globals['autor'] = '';".PHP_EOL;
		
		file_put_contents('settings.php', $config);
		_::$view->ajax(array('task' => 'make settings', 'result' => 'ok'));
	} elseif(!isset(_::$get['makeUser'])) {
		// make querys
		$querys = file_get_contents('others/install_data/db.sql');
		$querys = explode("\r\n".PHP_EOL, $querys);
		$querys = array_map('trim', $querys);
		$idQuery = _::$post['query']->int();
		
		if(isset($querys[$idQuery]))
		{
			$q = _::$db->query($querys[$idQuery]);
			_::$view->ajax(array('end' => false, 'task' => 'Query #'.$idQuery, 'result' => 'ok'));
		} else {
			_::$view->ajax(array('end' => true, 'task' => 'Install Finished', 'result' => 'ok'));
		}
	} else {
		// make user
		$usuario = new usuarios();
		$usuario->nick = strtolower(_::$post['nick']);
        $usuario->nombre = ' ';
        $usuario->email = 'admin@webmaster.local';
        $usuario->id_rango = 2; // Administrador
        $usuario->sexo = 1;
        $usuario->dia_n = 0;
        $usuario->mes_n = 0;
        $usuario->anio_n = 0;
        $usuario->pais = 1;
        $usuario->region = 'Desconocido';
        $usuario->status_user = 1; // 0 pendiente de email.
        $usuario->token_activacion = md5(base64_encode(mt_rand(10000, 999999).'TOKEN'));
        $usuario->puntos_obtenidos = 0;
        $usuario->puntos_disponibles = 0;
        $usuario->post_creados = 0;
        $usuario->comentarios_creados = 0;
        $usuario->seguidores = 0;
        $usuario->siguiendo = 0;
        $usuario->mensaje_perfil = ' ';
        $usuario->password = (string)_::$post['pass']->hash();
        $usuario->avatar = '/themes/default/images/default-avatar.jpg';
        $usuario->fecha_registro = time();
        // damos de alta el usuario
        $usuario->save();
		file_put_contents('install.log', 'READY');
	}
});
