<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class catalogo_calidades extends table
{
    // Primary keys
    protected $primaryKeys = 'id_calidad';

    // fields:
    public $id_calidad = null;
    public $id_categoria = null;
    public $nombre = null;
    public $css_icon = null;

}