<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class catalogo_idiomas extends table
{
    // Primary keys
    protected $primaryKeys = 'id_idioma';

    // fields:
    public $id_idioma = null;
    public $nombre = null;
    public $css_icon = null;

}