<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class catalogo_objeto extends table
{
    // Primary keys
    protected $primaryKeys = 'id_objeto';

    // fields:
    public $id_objeto = null;
    public $is_multiple = null;
    public $titulo = null;
    public $foto = null;
    public $id_idioma = null;
    public $is_online = null;
    public $id_categoria = null;
    public $id_calidad = null;
    public $id_post = null;
    
    protected $objectIdioma = null;
    protected $objectCalidad = null;
    protected $objectCategoria = null;
    
    public static function isInCatalog($idPost, $cate)
    {
        // si está como objeto individual
        if($cate->is_multiple == 0)
        {
            $r = self::getUnique('WHERE id_post = ?', array($idPost));
            if($r) return true;
            return false;
        } else {
            return catalogo_index_multiple::isInCatalog($idPost);
        }
    }
    
    public function getIdioma()
    {
        if(empty($this->objectIdioma)) $this->objectIdioma = new catalogo_idiomas($this->id_idioma);
        return $this->objectIdioma;
    }
    
    public function getCalidad()
    {
        if(empty($this->objectCalidad)) $this->objectCalidad = new catalogo_calidades($this->id_calidad);
        return $this->objectCalidad;
    }
    
    public function getCategoria()
    {
        if(empty($this->objectCategoria)) $this->objectCategoria = new categorias($this->id_categoria);
        return $this->objectCategoria;
    }
    
    public static function getObject($idPost, $cate)
    {
        // si está como objeto individual
        if($cate->is_multiple == 0)
        {
            $r = self::getUnique('WHERE id_post = ?', array($idPost));
            if($r) { return new catalogo_objeto($r['id_objeto']); } 
            return false;
        } else {
            return catalogo_index_multiple::getObject($idPost);
        }
    }

}