<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class catalogo_reportes extends table
{
    // Primary keys
    protected $primaryKeys = array('id_usuario', 'id_post');

    // fields:
    public $id_usuario = null;
    public $id_post = null;
    public $fecha = 0;
    
    static public function getMostReported($limit)
    {
        $q = self::$pdo->prepare('SELECT id_post, count(id_usuario) as SCantidad FROM catalogo_reportes GROUP BY id_post ORDER BY SCantidad DESC LIMIT '.$limit);
        $q->execute();
        $r = $q->fetchAll(PDO::FETCH_ASSOC);
        return _::factory($r, 'id_post', 'post');
    }

}