<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class catalogo_index_multiple extends table
{
    // Primary keys
    protected $primaryKeys = array('id_objeto', 'id_post');

    // fields:
    public $id_objeto = null;
    public $id_post = null;
    public $temporada = null;
    public $capitulo = null;
    public $uploaded = 0;
    
    public static function isInCatalog($idPost)
    {
        $r = self::getUnique('WHERE id_post = ?', array($idPost));
        if($r) return true;
        return false;
    }
    
    public static function getObject($idPost)
    {
        $r = self::getUnique('WHERE id_post = ?', array($idPost));
        if($r) { return new catalogo_objeto($r['id_objeto']); }
        return false;
    }

    public static function getTemporadas($objeto)
    {

        $q = self::$pdo->prepare('SELECT temporada FROM catalogo_index_multiple WHERE id_objeto = ? GROUP BY temporada');
        $q->execute(array($objeto->id_objeto));
        $out = array();
        foreach($q->fetchAll(PDO::FETCH_ASSOC) as $temporada)
        {
            $out[$temporada['temporada']] = $temporada['temporada'];
        }
        return $out;
    }
    
    public static function getCaps($obj, $temporada)
    {
        $q = self::getAll('WHERE id_objeto = ? AND temporada = ? ORDER BY capitulo DESC', array($obj->id_objeto, $temporada));
        foreach($q as $cap)
        {
            $out[$cap['capitulo']] = new post($cap['id_post']);
        }
        return $out;
    }
}