<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class medals extends table
{
    // Primary keys
    protected $primaryKeys = 'id_medalla';

    // fields:
    public $id_medalla = null;
    public $nombre = null;
    public $foto = null;
    public $razon = null;

}