<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class security extends table
{
    // Primary keys
    protected $primaryKeys = 'id_reporte';

    // fields:
    public $id_reporte = null;
    public $titulo = null;
    public $descripcion = null;
    public $autor = null;
    public $fecha_reporte = null;
    public $relevancia = null;
    
    public $authObject = null;
    
    public function autor()
    {
        if($this->autor > 0)
        {
            if(empty($this->authObject)) $this->authObject = new usuarios($this->autor);
            return $this->authObject;
        }
        $usuario = new usuarios();
        $usuario->id_usuario = 0;
        $usuario->nick = '-Visitante-';
        $usuario->nick_seo = 'undefined';
        return $usuario;
    }
    
    public function fecha()
    {
        return date('H:i d/m/Y', $this->fecha_reporte);
    }
    
    static public function advertir($titulo, $descripcion = ' ', $autor = 0)
    {
        $report = new security();
        $report->titulo = $titulo;
        $report->descripcion = $descripcion;
        $report->autor = $autor;
        $report->fecha_reporte = time();
        $report->relevancia = 1;
    }
    
    static public function notificar($titulo, $descripcion = ' ', $autor = 0)
    {
        $report = new security();
        $report->titulo = $titulo;
        $report->descripcion = $descripcion;
        $report->autor = $autor;
        $report->fecha_reporte = time();
        $report->relevancia = 0;
    }
    
    static public function fatalidad($titulo, $descripcion = ' ', $autor = 0)
    {
        $report = new security();
        $report->titulo = $titulo;
        $report->descripcion = $descripcion;
        $report->autor = $autor;
        $report->fecha_reporte = time();
        $report->relevancia = 2;
    }

}