<?php class_exists('_') || die('FORBIDDEN');

// model autogenerated by model_maker.php
class user_medals extends table
{
    // Primary keys
    protected $primaryKeys = array('id_medalla', 'id_usuario');

    // fields:
    public $id_medalla = null;
    public $id_usuario = null;
    public $fecha = null;

}